services:
  # Web Backend API
  kr.hanyang.mindwatch.api:
    container_name: Mindwatch-API
    image: ${DOCKER_REGISTRY-}krhanyangmindwatchapi
    build:
      context: .
      dockerfile: KR.Hanyang.Mindwatch.Api/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    depends_on:
      - kr.hanyang.mindwatch.mlservice
      - database
    networks:
      - database
      - mlservice

  # SQL Server 2022
  database:
    container_name: Mindwatch-Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mindwatch_1234
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - database

  # Web Frontend
  kr.hanyang.mindwatch.frontend:
    container_name: Mindwatch-Frontend
    build:
      context: Kr.Hanyang.Mindwatch.Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./KR.Hanyang.Mindwatch.Frontend:/app
      - /app/node_modules
    depends_on:
      - kr.hanyang.mindwatch.api

  # Ml Service
  kr.hanyang.mindwatch.mlservice:
    container_name: Mindwatch-MlService
    build:
      context: Kr.Hanyang.Mindwatch.MlService
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    networks:
      - mlservice

networks:
  database:
    driver: bridge
  mlservice:
    driver: bridge

volumes:
  sqlserver-data:
